version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: goomerRedis_development
    ports:
      - 6379:6379

  database:
    image: postgres
    container_name: goomerListaRangoDB_development
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: goomer_lista_rango
    volumes:
      - ./src/shared/infra/databases/postgreSQL/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    image: node:alpine
    container_name: goomerListaRangoAPI_development
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    volumes:
      - "/app/node_modules"
      - .:/app
    environment:
      - REDIS_HOST=goomerRedis_development
      - POSTGRESQL_HOST=goomerListaRangoDB_development
      - NODE_ENV=dev
    depends_on:
      - database
      - redis
