version: '3.8'

services:
  redis:
    image: bitnami/redis:latest
    container_name: goomerRedis_production
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  database:
    image: bitnami/postgresql:latest
    container_name: goomerListaRangoDB_production
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
    volumes:
      - ./src/shared/infra/databases/postgreSQL/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    image: node:14
    container_name: goomerListaRangoAPI_production
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - 3333:3333
    volumes:
      - "/app/node_modules"
      - .:/app
    environment:
      - REDIS_HOST=goomerRedis_production
      - POSTGRESQL_HOST=goomerListaRangoDB_production
    depends_on:
      - database
      - redis
